keys:
  - &svr1shaikh age18cfmzsc7x57aqyjzrgwqmmzk8chcemwtq2psdksnd7wy9ehxeymsyqtamq
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *svr1shaikh
